dubbo:
  application:
    name: dubbo_user_consumer
    qos-enable: false
  protocol:
    name: dubbo
    port: -1 # -1 表示端口自动配置，避免冲突
  registry:
    address: zookeeper://${zookeeper.address}:${zookeeper.port}
  config-center:
    address: zookeeper://${zookeeper.address}:${zookeeper.port}